language: node_js
node_js:
  - "node"
services:
  - postgresql
notifications:
  email: false
before_script:
  - psql -c 'create database testing_db;' -U postgres
script:
  - npm test
addons:
  postgresql: "9.5"
