language: node_js
node_js:
  - "node"
env:
  - DATABASE_URL=pgsql
services:
  - postgresql
postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres
before_script:
  - "psql -c 'create database myapp_test;' -U postgres"
  - "rake db:migrate"
